[package]
name = "zk-time-capsule-server"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", branch = "dev" }
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
